LeaveAreaOnDisconnecting: true
DominationAlertDelay: 300
Regions:
Messages:
  Warnings:
    DominatingMessageSingular: "&eClan {CLAN} has been dominating {AREA} for {TIME} minutes with {MEMBERS} members"
    DominatingMessagePlural: "&eClans {CLAN} have been dominating {AREA} for {TIME} minutes with {MEMBERS} members"
    TeamsJoiner: ", "
    LastTeamJoiner: " and "
    PositionSet: "&aPosition set successfully. Dont forget to use &f/ClanDominanceAlert reload"
    Reloaded: "&aConfig was reloaded successfully"
  Errors:
    NotAllowed: "&cNot allowed"
    WrongIndex: "&cIndex must be 1 or 2"
    MustBePlayer: "&cOnly players can execute this command"
  Usage:
    SetPosition: "&eUsage: /ClanDominanceAlert set <name> <index:1/2>"
    Reload: "&eUsage: /ClanDominanceAlert reload"